/** @type {import('tailwindcss').Config} */
export default {
  content: ['./njk/**/*.{njk,md,html,js}', './js/**/*.js', './eleventy/**/*.js'],
  theme: {
    extend: {
      // Design tokens will be auto-generated by Figma services
      // Colors are managed in styles/colors.css via PaletteService.js
      // Typography is managed in styles/typography/ via TypographyService.js

      // Container queries for responsive design
      containers: {
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
      },

      // Animation timing for GSAP integration
      transitionTimingFunction: {
        'gsap-ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'gsap-bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },

      // Z-index scale for layering
      zIndex: {
        header: '100',
        navigation: '200',
        modal: '300',
        tooltip: '400',
      },
    },
  },
  plugins: [
    // Custom mask utilities plugin
    function ({ addUtilities }) {
      addUtilities({
        '.mask-radial': {
          'mask-image': 'radial-gradient(circle, black 50%, transparent 50%)',
        },
        '.mask-linear': {
          'mask-image': 'linear-gradient(to right, black 0%, transparent 100%)',
        },
      });
    },
  ],

  // CSS 4.0 optimizations
  experimental: {
    optimizeUniversalDefaults: true,
  },

  // Ensure compatibility with Figma design system integration
  corePlugins: {
    // Let Figma services handle color generation
    colors: false,
  },
};
