/**
 * ---
 * aix:
 *   id: frontend.tailwind-config
 *   role: Tailwind configuration for the frontend build.
 *   status: stable
 *   surface: internal
 *   scope: frontend
 *   runtime: node
 *   tags:
 *     - frontend
 *     - tailwind.config.js
 * ---
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./njk/**/*.{njk,md,html,js}', './js/**/*.js', './eleventy/**/*.js'],
  theme: {
    extend: {
      // Design tokens will be auto-generated by Figma services
      // Colors are managed in styles/colors.css via PaletteService.js
      // Typography is managed in styles/typography/ via TypographyService.js

      // Container queries for responsive design
      containers: {
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
      },

      // Animation timing for GSAP integration
      transitionTimingFunction: {
        'gsap-ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'gsap-bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },

      // Z-index scale for layering
      zIndex: {
        header: '100',
        navigation: '200',
        modal: '300',
        tooltip: '400',
      },

      // Mask utilities (defined in styles/plugins/mask.css with @utility)
      maskImage: {
        grunge: 'var(--mask-grunge)',
        'gradient-vertical': 'var(--mask-gradient-vertical)',
        'gradient-horizontal': 'var(--mask-gradient-horizontal)',
        radial: 'var(--mask-radial)',
      },
      maskMode: {
        luminance: 'luminance',
        alpha: 'alpha',
      },
      maskSize: {
        auto: 'auto',
        cover: 'cover',
        contain: 'contain',
      },
      maskPosition: {
        center: 'center',
        top: 'top',
        bottom: 'bottom',
        left: 'left',
        right: 'right',
        'top-left': 'top left',
        'top-right': 'top right',
        'bottom-left': 'bottom left',
        'bottom-right': 'bottom right',
      },
      maskRepeat: {
        repeat: 'repeat',
        'no-repeat': 'no-repeat',
        'repeat-x': 'repeat-x',
        'repeat-y': 'repeat-y',
      },
      maskClip: {
        border: 'border-box',
        padding: 'padding-box',
        content: 'content-box',
        text: 'text',
      },
      maskComposite: {
        add: 'add',
        subtract: 'subtract',
        intersect: 'intersect',
        exclude: 'exclude',
      },
    },
  },
  plugins: [],

  // CSS 4.0 optimizations
  experimental: {
    optimizeUniversalDefaults: true,
  },

  // Ensure compatibility with Figma design system integration
  corePlugins: {
    // Let Figma services handle color generation
    colors: false,
  },
};
