/** @format */

/**
 * Choreography Event Contracts
 *
 * Core event values that define the choreography API and conventions.
 *
 * Section events follow the `${section}:${phase}:${state}` naming convention
 * and are generated by `makeSectionEvents` so every section exposes an
 * identical, typo-free shape. Add a new section by adding one line to the
 * EVENTS map below — never hand-type the ten keys.
 */

/**
 * Build the standard event-name set for a section.
 *
 * @param {string} key - Section key (e.g. "bio", "awards").
 * @returns {{
 *   enter: string, exit: string,
 *   onEnterBack: string, onLeaveBack: string,
 *   landingStart: string, landingComplete: string,
 *   introStart: string, introComplete: string,
 *   outroStart: string, outroComplete: string,
 * }}
 */
export function makeSectionEvents(key) {
  return {
    enter: `${key}:enter`,
    exit: `${key}:exit`,
    // Historical naming: kept camelCase for back-compat with existing listeners.
    onEnterBack: `${key}:onEnterBack`,
    onLeaveBack: `${key}:onLeaveBack`,
    landingStart: `${key}:landing:start`,
    landingComplete: `${key}:landing:complete`,
    introStart: `${key}:intro:start`,
    introComplete: `${key}:intro:complete`,
    outroStart: `${key}:outro:start`,
    outroComplete: `${key}:outro:complete`,
  };
}

/**
 * Background video media events (BackgroundVideo).
 *
 * Distinct from the section lifecycle above: those track the *reveal*
 * choreography, these track the <video> element's own playstate. They are the
 * only events that cross out of the choreography module graph — BackgroundVideo
 * mirrors each one to `window` as a CustomEvent so the preloader, which boots
 * before the Director exists and therefore has no bus, can gate on them.
 *
 * `unavailable` is the negative-space signal: no video element, no src to play,
 * or a refused play(). A consumer gating on playback must treat it as "stop
 * waiting", or it will wait out its own timeout on a page that has no video.
 */
const VIDEO_MEDIA_EVENTS = {
  ready: "video:media:ready",
  playing: "video:media:playing",
  pause: "video:media:pause",
  waiting: "video:media:waiting",
  error: "video:media:error",
  unavailable: "video:media:unavailable",
};

export const EVENTS = {
  system: {
    preloaderOut: "preloader:out",
    directorReady: "director:ready",
    // Dispatched on `window` by the preloader once it has assigned the deferred
    // src to the background video. The preloader owns hydration (a bandwidth
    // staging concern); BackgroundVideo owns everything after it, and uses this
    // as its cue to evaluate the element and start playback.
    preloaderVideoHydrated: "preloader:video:hydrated",
  },
  video: { ...makeSectionEvents("video"), media: VIDEO_MEDIA_EVENTS },
  // Home landing header role state machine (HomeHeaderManager). The nav reveal
  // emits intro:start/complete so a larger sequence can coordinate off it.
  home: makeSectionEvents("home"),
  hero: makeSectionEvents("hero"),
  organizations: makeSectionEvents("organizations"),
  bio: makeSectionEvents("bio"),
  process: makeSectionEvents("process"),
  awards: makeSectionEvents("awards"),
  work: makeSectionEvents("work"),
  // Work section local navigation (WorkNavManager scrollspy). Broadcasts the
  // active child group as { id, seeded } — seeded: true marks the boot
  // default, not a scroll-derived position; id: null means no group is in
  // the active band. WorkHeaderManager reads it for the drawer handle's
  // title below md.
  workNav: {
    activeChange: "work:nav:active",
  },
};
