/** @format */

/**
 * Choreography Event Contracts
 *
 * Core event values that define the choreography API and conventions.
 *
 * Section events follow the `${section}:${phase}:${state}` naming convention
 * and are generated by `makeSectionEvents` so every section exposes an
 * identical, typo-free shape. Add a new section by adding one line to the
 * EVENTS map below — never hand-type the ten keys.
 */

/**
 * Build the standard event-name set for a section.
 *
 * @param {string} key - Section key (e.g. "bio", "awards").
 * @returns {{
 *   enter: string, exit: string,
 *   onEnterBack: string, onLeaveBack: string,
 *   landingStart: string, landingComplete: string,
 *   introStart: string, introComplete: string,
 *   outroStart: string, outroComplete: string,
 * }}
 */
export function makeSectionEvents(key) {
  return {
    enter: `${key}:enter`,
    exit: `${key}:exit`,
    // Historical naming: kept camelCase for back-compat with existing listeners.
    onEnterBack: `${key}:onEnterBack`,
    onLeaveBack: `${key}:onLeaveBack`,
    landingStart: `${key}:landing:start`,
    landingComplete: `${key}:landing:complete`,
    introStart: `${key}:intro:start`,
    introComplete: `${key}:intro:complete`,
    outroStart: `${key}:outro:start`,
    outroComplete: `${key}:outro:complete`,
  };
}

export const EVENTS = {
  system: {
    preloaderOut: "preloader:out",
    directorReady: "director:ready",
  },
  video: makeSectionEvents("video"),
  // Home landing header role state machine (HomeHeaderManager). The nav reveal
  // emits intro:start/complete so a larger sequence can coordinate off it.
  home: makeSectionEvents("home"),
  hero: makeSectionEvents("hero"),
  organizations: makeSectionEvents("organizations"),
  bio: makeSectionEvents("bio"),
  process: makeSectionEvents("process"),
  awards: makeSectionEvents("awards"),
  work: makeSectionEvents("work"),
  // Work section local navigation (WorkNavManager scrollspy). Broadcasts the
  // active child group so future surfaces (lg rail, sm disclosure) can react.
  workNav: {
    activeChange: "work:nav:active",
  },
};
